from __future__ import annotations

from typing import Protocol

from .models import CapturedRequest


class CookieMonsterHooks(Protocol):
    def on_capture_start(self) -> None: ...
    def on_capture_item(self, capture: CapturedRequest) -> None: ...
    def on_capture_end(self, total: int) -> None: ...
    def on_replay_attempt(self, attempt: int, max_attempts: int) -> None: ...
    def on_replay_end(self, status_code: int) -> None: ...
